// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX9OzQgt-o2hKUd6rHJzaa03DGbycEfk0',
    appId: '1:1023730180508:android:315045b887815a98dde859',
    messagingSenderId: '1023730180508',
    projectId: 'fit-2022-23',
    storageBucket: 'fit-2022-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Kwgqli6hXHyoBVyngqlGFjUZ6hpQzew',
    appId: '1:1023730180508:ios:576373fcf7938e70dde859',
    messagingSenderId: '1023730180508',
    projectId: 'fit-2022-23',
    storageBucket: 'fit-2022-23.appspot.com',
    androidClientId: '1023730180508-tjrmslbpa0bqev0p4gnijf9bd46pnpt1.apps.googleusercontent.com',
    iosClientId: '1023730180508-243gdi086ukk1m5qj3o84pf76ts546el.apps.googleusercontent.com',
    iosBundleId: 'com.example.fraternityOfInformationTechnology',
  );
}
